export enum ActionType {
  CHANGE_SETTING = 'CHANGE_SETTING',
  TOGGLE_ANSWER_CHECKED = 'TOGGLE_ANSWER_CHECKED',
  TOGGLE_ANSWER_CORRECT = 'TOGGLE_ANSWER_CORRECT',
  PROGRESS_TRAINING = 'PROGRESS_TRAINING',
  RESET_TRAINING = 'RESET_TRAINING',
  SET_INPUT_WORD = 'SET_INPUT_WORD',
  TOGGLE_MOVE_TO_NEXT = 'TOGGLE_MOVE_TO_NEXT',
  TOGGLE_TRAINING_STATISTIC = 'TOGGLE_TRAINING_STATISTIC',
  ADD_TO_FAILED_TRAINING = 'ADD_TO_FAILED_TRAINING',
  ADD_TO_SUCCESS_TRAINING = 'ADD_TO_SUCCESS_TRAINING',
  ADD_ROW_OF_SUCCESS = 'ADD_ROW_OF_SUCCESS',
}
