export enum ActionType {
  SET_NEW_USER = 'SET_NEW_USER',
  SET_USER_NAME = 'SET_USER_NAME',
  SET_REFRESH_TOKEN = 'SET_REFRESH_TOKEN',
  REMOVE_TOKEN = 'REMOVE_TOKEN',
  SET_LOGGED = 'SET_LOGGED',
  SET_UNLOGGED = 'SET_UNLOGGED',
  ADD_API_ERROR_MESSAGE = 'ADD_API_ERROR_MESSAGE',
  REMOVE_API_ERROR_MESSAGE = 'REMOVE_API_ERROR_MESSAGE',
}
