import { IntialStateUserWords } from 'containers/TrainingCard/models';
import { InitialStateSettings, InitialStateUserStatistic } from 'containers/Authorisation/models';

export interface State {
  trainingSettings;
  trainingStatistic;
  training;
  app;
  appErr;
  appUserWords: IntialStateUserWords;
  appUserSettings: InitialStateSettings;
  appUserStatistic: InitialStateUserStatistic;
  authToken;
  appVisit;
  authErrors;
  appTraining;
  authLog;
  authName;
  mainModal;
  mainModalInfo;
  mainTheme;
  mainSettings;
  mainSettLoader;
  mainSetEnabled;
  mainCardsWords;
  mainLang;
  mainReg;
  mainLog;
  mainStudyMode;
  audioCallPage;
  audioCallLevel;
  audioCallRound;
  audioCallCurrWords;
  audioCallAnswer;
  audioCallStatistic;
  audioCallLongStatistic;
  audioCallModal;
  engPuzzleBtns;
  engPuzzleActiveIdx;
  engPuzzleControlBtns;
  engPuzzleCards;
  engPuzzlePage;
  engPuzzleGroup;
  engPuzzleXOffset;
  engPuzzleSolved;
  engPuzzleFailed;
  engPuzzleSuccess;
  engPuzzleResults;
  engPuzzleStatistic;
  engPuzzleStatisticInfo;
  engPuzzleFetchedWords;
  engPuzzleLoading;
  engPuzzleStartPage;
  dictionaryState;
  speakItControl;
  speakItFetch;
  speakItWord;
  speakItButtons;
  mainErrorModal;
  speakItStatisticInfo;
  speakItStatistic;
  // add more fields according rootReducer
}
